/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.hawk.service.ifc.api;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-04-12")
public class IFCExportOptions implements org.apache.thrift.TBase<IFCExportOptions, IFCExportOptions._Fields>, java.io.Serializable, Cloneable, Comparable<IFCExportOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IFCExportOptions");

  private static final org.apache.thrift.protocol.TField REPOSITORY_PATTERN_FIELD_DESC = new org.apache.thrift.protocol.TField("repositoryPattern", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField FILE_PATTERNS_FIELD_DESC = new org.apache.thrift.protocol.TField("filePatterns", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField INCLUDE_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("includeRules", org.apache.thrift.protocol.TType.MAP, (short)3);
  private static final org.apache.thrift.protocol.TField EXCLUDE_RULES_FIELD_DESC = new org.apache.thrift.protocol.TField("excludeRules", org.apache.thrift.protocol.TType.MAP, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IFCExportOptionsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IFCExportOptionsTupleSchemeFactory());
  }

  public String repositoryPattern; // optional
  public List<String> filePatterns; // optional
  public Map<String,Map<String,Set<String>>> includeRules; // optional
  public Map<String,Map<String,Set<String>>> excludeRules; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REPOSITORY_PATTERN((short)1, "repositoryPattern"),
    FILE_PATTERNS((short)2, "filePatterns"),
    INCLUDE_RULES((short)3, "includeRules"),
    EXCLUDE_RULES((short)4, "excludeRules");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REPOSITORY_PATTERN
          return REPOSITORY_PATTERN;
        case 2: // FILE_PATTERNS
          return FILE_PATTERNS;
        case 3: // INCLUDE_RULES
          return INCLUDE_RULES;
        case 4: // EXCLUDE_RULES
          return EXCLUDE_RULES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.REPOSITORY_PATTERN,_Fields.FILE_PATTERNS,_Fields.INCLUDE_RULES,_Fields.EXCLUDE_RULES};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REPOSITORY_PATTERN, new org.apache.thrift.meta_data.FieldMetaData("repositoryPattern", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.FILE_PATTERNS, new org.apache.thrift.meta_data.FieldMetaData("filePatterns", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.INCLUDE_RULES, new org.apache.thrift.meta_data.FieldMetaData("includeRules", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
                new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))))));
    tmpMap.put(_Fields.EXCLUDE_RULES, new org.apache.thrift.meta_data.FieldMetaData("excludeRules", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
                new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
                    new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IFCExportOptions.class, metaDataMap);
  }

  public IFCExportOptions() {
    this.repositoryPattern = "*";

  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IFCExportOptions(IFCExportOptions other) {
    if (other.isSetRepositoryPattern()) {
      this.repositoryPattern = other.repositoryPattern;
    }
    if (other.isSetFilePatterns()) {
      List<String> __this__filePatterns = new ArrayList<String>(other.filePatterns);
      this.filePatterns = __this__filePatterns;
    }
    if (other.isSetIncludeRules()) {
      Map<String,Map<String,Set<String>>> __this__includeRules = new HashMap<String,Map<String,Set<String>>>(other.includeRules.size());
      for (Map.Entry<String, Map<String,Set<String>>> other_element : other.includeRules.entrySet()) {

        String other_element_key = other_element.getKey();
        Map<String,Set<String>> other_element_value = other_element.getValue();

        String __this__includeRules_copy_key = other_element_key;

        Map<String,Set<String>> __this__includeRules_copy_value = new HashMap<String,Set<String>>(other_element_value.size());
        for (Map.Entry<String, Set<String>> other_element_value_element : other_element_value.entrySet()) {

          String other_element_value_element_key = other_element_value_element.getKey();
          Set<String> other_element_value_element_value = other_element_value_element.getValue();

          String __this__includeRules_copy_value_copy_key = other_element_value_element_key;

          Set<String> __this__includeRules_copy_value_copy_value = new HashSet<String>(other_element_value_element_value);

          __this__includeRules_copy_value.put(__this__includeRules_copy_value_copy_key, __this__includeRules_copy_value_copy_value);
        }

        __this__includeRules.put(__this__includeRules_copy_key, __this__includeRules_copy_value);
      }
      this.includeRules = __this__includeRules;
    }
    if (other.isSetExcludeRules()) {
      Map<String,Map<String,Set<String>>> __this__excludeRules = new HashMap<String,Map<String,Set<String>>>(other.excludeRules.size());
      for (Map.Entry<String, Map<String,Set<String>>> other_element : other.excludeRules.entrySet()) {

        String other_element_key = other_element.getKey();
        Map<String,Set<String>> other_element_value = other_element.getValue();

        String __this__excludeRules_copy_key = other_element_key;

        Map<String,Set<String>> __this__excludeRules_copy_value = new HashMap<String,Set<String>>(other_element_value.size());
        for (Map.Entry<String, Set<String>> other_element_value_element : other_element_value.entrySet()) {

          String other_element_value_element_key = other_element_value_element.getKey();
          Set<String> other_element_value_element_value = other_element_value_element.getValue();

          String __this__excludeRules_copy_value_copy_key = other_element_value_element_key;

          Set<String> __this__excludeRules_copy_value_copy_value = new HashSet<String>(other_element_value_element_value);

          __this__excludeRules_copy_value.put(__this__excludeRules_copy_value_copy_key, __this__excludeRules_copy_value_copy_value);
        }

        __this__excludeRules.put(__this__excludeRules_copy_key, __this__excludeRules_copy_value);
      }
      this.excludeRules = __this__excludeRules;
    }
  }

  public IFCExportOptions deepCopy() {
    return new IFCExportOptions(this);
  }

  @Override
  public void clear() {
    this.repositoryPattern = "*";

    this.filePatterns = null;
    this.includeRules = null;
    this.excludeRules = null;
  }

  public String getRepositoryPattern() {
    return this.repositoryPattern;
  }

  public IFCExportOptions setRepositoryPattern(String repositoryPattern) {
    this.repositoryPattern = repositoryPattern;
    return this;
  }

  public void unsetRepositoryPattern() {
    this.repositoryPattern = null;
  }

  /** Returns true if field repositoryPattern is set (has been assigned a value) and false otherwise */
  public boolean isSetRepositoryPattern() {
    return this.repositoryPattern != null;
  }

  public void setRepositoryPatternIsSet(boolean value) {
    if (!value) {
      this.repositoryPattern = null;
    }
  }

  public int getFilePatternsSize() {
    return (this.filePatterns == null) ? 0 : this.filePatterns.size();
  }

  public java.util.Iterator<String> getFilePatternsIterator() {
    return (this.filePatterns == null) ? null : this.filePatterns.iterator();
  }

  public void addToFilePatterns(String elem) {
    if (this.filePatterns == null) {
      this.filePatterns = new ArrayList<String>();
    }
    this.filePatterns.add(elem);
  }

  public List<String> getFilePatterns() {
    return this.filePatterns;
  }

  public IFCExportOptions setFilePatterns(List<String> filePatterns) {
    this.filePatterns = filePatterns;
    return this;
  }

  public void unsetFilePatterns() {
    this.filePatterns = null;
  }

  /** Returns true if field filePatterns is set (has been assigned a value) and false otherwise */
  public boolean isSetFilePatterns() {
    return this.filePatterns != null;
  }

  public void setFilePatternsIsSet(boolean value) {
    if (!value) {
      this.filePatterns = null;
    }
  }

  public int getIncludeRulesSize() {
    return (this.includeRules == null) ? 0 : this.includeRules.size();
  }

  public void putToIncludeRules(String key, Map<String,Set<String>> val) {
    if (this.includeRules == null) {
      this.includeRules = new HashMap<String,Map<String,Set<String>>>();
    }
    this.includeRules.put(key, val);
  }

  public Map<String,Map<String,Set<String>>> getIncludeRules() {
    return this.includeRules;
  }

  public IFCExportOptions setIncludeRules(Map<String,Map<String,Set<String>>> includeRules) {
    this.includeRules = includeRules;
    return this;
  }

  public void unsetIncludeRules() {
    this.includeRules = null;
  }

  /** Returns true if field includeRules is set (has been assigned a value) and false otherwise */
  public boolean isSetIncludeRules() {
    return this.includeRules != null;
  }

  public void setIncludeRulesIsSet(boolean value) {
    if (!value) {
      this.includeRules = null;
    }
  }

  public int getExcludeRulesSize() {
    return (this.excludeRules == null) ? 0 : this.excludeRules.size();
  }

  public void putToExcludeRules(String key, Map<String,Set<String>> val) {
    if (this.excludeRules == null) {
      this.excludeRules = new HashMap<String,Map<String,Set<String>>>();
    }
    this.excludeRules.put(key, val);
  }

  public Map<String,Map<String,Set<String>>> getExcludeRules() {
    return this.excludeRules;
  }

  public IFCExportOptions setExcludeRules(Map<String,Map<String,Set<String>>> excludeRules) {
    this.excludeRules = excludeRules;
    return this;
  }

  public void unsetExcludeRules() {
    this.excludeRules = null;
  }

  /** Returns true if field excludeRules is set (has been assigned a value) and false otherwise */
  public boolean isSetExcludeRules() {
    return this.excludeRules != null;
  }

  public void setExcludeRulesIsSet(boolean value) {
    if (!value) {
      this.excludeRules = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case REPOSITORY_PATTERN:
      if (value == null) {
        unsetRepositoryPattern();
      } else {
        setRepositoryPattern((String)value);
      }
      break;

    case FILE_PATTERNS:
      if (value == null) {
        unsetFilePatterns();
      } else {
        setFilePatterns((List<String>)value);
      }
      break;

    case INCLUDE_RULES:
      if (value == null) {
        unsetIncludeRules();
      } else {
        setIncludeRules((Map<String,Map<String,Set<String>>>)value);
      }
      break;

    case EXCLUDE_RULES:
      if (value == null) {
        unsetExcludeRules();
      } else {
        setExcludeRules((Map<String,Map<String,Set<String>>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case REPOSITORY_PATTERN:
      return getRepositoryPattern();

    case FILE_PATTERNS:
      return getFilePatterns();

    case INCLUDE_RULES:
      return getIncludeRules();

    case EXCLUDE_RULES:
      return getExcludeRules();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case REPOSITORY_PATTERN:
      return isSetRepositoryPattern();
    case FILE_PATTERNS:
      return isSetFilePatterns();
    case INCLUDE_RULES:
      return isSetIncludeRules();
    case EXCLUDE_RULES:
      return isSetExcludeRules();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IFCExportOptions)
      return this.equals((IFCExportOptions)that);
    return false;
  }

  public boolean equals(IFCExportOptions that) {
    if (that == null)
      return false;

    boolean this_present_repositoryPattern = true && this.isSetRepositoryPattern();
    boolean that_present_repositoryPattern = true && that.isSetRepositoryPattern();
    if (this_present_repositoryPattern || that_present_repositoryPattern) {
      if (!(this_present_repositoryPattern && that_present_repositoryPattern))
        return false;
      if (!this.repositoryPattern.equals(that.repositoryPattern))
        return false;
    }

    boolean this_present_filePatterns = true && this.isSetFilePatterns();
    boolean that_present_filePatterns = true && that.isSetFilePatterns();
    if (this_present_filePatterns || that_present_filePatterns) {
      if (!(this_present_filePatterns && that_present_filePatterns))
        return false;
      if (!this.filePatterns.equals(that.filePatterns))
        return false;
    }

    boolean this_present_includeRules = true && this.isSetIncludeRules();
    boolean that_present_includeRules = true && that.isSetIncludeRules();
    if (this_present_includeRules || that_present_includeRules) {
      if (!(this_present_includeRules && that_present_includeRules))
        return false;
      if (!this.includeRules.equals(that.includeRules))
        return false;
    }

    boolean this_present_excludeRules = true && this.isSetExcludeRules();
    boolean that_present_excludeRules = true && that.isSetExcludeRules();
    if (this_present_excludeRules || that_present_excludeRules) {
      if (!(this_present_excludeRules && that_present_excludeRules))
        return false;
      if (!this.excludeRules.equals(that.excludeRules))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_repositoryPattern = true && (isSetRepositoryPattern());
    list.add(present_repositoryPattern);
    if (present_repositoryPattern)
      list.add(repositoryPattern);

    boolean present_filePatterns = true && (isSetFilePatterns());
    list.add(present_filePatterns);
    if (present_filePatterns)
      list.add(filePatterns);

    boolean present_includeRules = true && (isSetIncludeRules());
    list.add(present_includeRules);
    if (present_includeRules)
      list.add(includeRules);

    boolean present_excludeRules = true && (isSetExcludeRules());
    list.add(present_excludeRules);
    if (present_excludeRules)
      list.add(excludeRules);

    return list.hashCode();
  }

  @Override
  public int compareTo(IFCExportOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRepositoryPattern()).compareTo(other.isSetRepositoryPattern());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRepositoryPattern()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.repositoryPattern, other.repositoryPattern);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFilePatterns()).compareTo(other.isSetFilePatterns());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilePatterns()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filePatterns, other.filePatterns);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIncludeRules()).compareTo(other.isSetIncludeRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIncludeRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.includeRules, other.includeRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExcludeRules()).compareTo(other.isSetExcludeRules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExcludeRules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.excludeRules, other.excludeRules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IFCExportOptions(");
    boolean first = true;

    if (isSetRepositoryPattern()) {
      sb.append("repositoryPattern:");
      if (this.repositoryPattern == null) {
        sb.append("null");
      } else {
        sb.append(this.repositoryPattern);
      }
      first = false;
    }
    if (isSetFilePatterns()) {
      if (!first) sb.append(", ");
      sb.append("filePatterns:");
      if (this.filePatterns == null) {
        sb.append("null");
      } else {
        sb.append(this.filePatterns);
      }
      first = false;
    }
    if (isSetIncludeRules()) {
      if (!first) sb.append(", ");
      sb.append("includeRules:");
      if (this.includeRules == null) {
        sb.append("null");
      } else {
        sb.append(this.includeRules);
      }
      first = false;
    }
    if (isSetExcludeRules()) {
      if (!first) sb.append(", ");
      sb.append("excludeRules:");
      if (this.excludeRules == null) {
        sb.append("null");
      } else {
        sb.append(this.excludeRules);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IFCExportOptionsStandardSchemeFactory implements SchemeFactory {
    public IFCExportOptionsStandardScheme getScheme() {
      return new IFCExportOptionsStandardScheme();
    }
  }

  private static class IFCExportOptionsStandardScheme extends StandardScheme<IFCExportOptions> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IFCExportOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REPOSITORY_PATTERN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.repositoryPattern = iprot.readString();
              struct.setRepositoryPatternIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // FILE_PATTERNS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.filePatterns = new ArrayList<String>(_list0.size);
                String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.filePatterns.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setFilePatternsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // INCLUDE_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map3 = iprot.readMapBegin();
                struct.includeRules = new HashMap<String,Map<String,Set<String>>>(2*_map3.size);
                String _key4;
                Map<String,Set<String>> _val5;
                for (int _i6 = 0; _i6 < _map3.size; ++_i6)
                {
                  _key4 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TMap _map7 = iprot.readMapBegin();
                    _val5 = new HashMap<String,Set<String>>(2*_map7.size);
                    String _key8;
                    Set<String> _val9;
                    for (int _i10 = 0; _i10 < _map7.size; ++_i10)
                    {
                      _key8 = iprot.readString();
                      {
                        org.apache.thrift.protocol.TSet _set11 = iprot.readSetBegin();
                        _val9 = new HashSet<String>(2*_set11.size);
                        String _elem12;
                        for (int _i13 = 0; _i13 < _set11.size; ++_i13)
                        {
                          _elem12 = iprot.readString();
                          _val9.add(_elem12);
                        }
                        iprot.readSetEnd();
                      }
                      _val5.put(_key8, _val9);
                    }
                    iprot.readMapEnd();
                  }
                  struct.includeRules.put(_key4, _val5);
                }
                iprot.readMapEnd();
              }
              struct.setIncludeRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // EXCLUDE_RULES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map14 = iprot.readMapBegin();
                struct.excludeRules = new HashMap<String,Map<String,Set<String>>>(2*_map14.size);
                String _key15;
                Map<String,Set<String>> _val16;
                for (int _i17 = 0; _i17 < _map14.size; ++_i17)
                {
                  _key15 = iprot.readString();
                  {
                    org.apache.thrift.protocol.TMap _map18 = iprot.readMapBegin();
                    _val16 = new HashMap<String,Set<String>>(2*_map18.size);
                    String _key19;
                    Set<String> _val20;
                    for (int _i21 = 0; _i21 < _map18.size; ++_i21)
                    {
                      _key19 = iprot.readString();
                      {
                        org.apache.thrift.protocol.TSet _set22 = iprot.readSetBegin();
                        _val20 = new HashSet<String>(2*_set22.size);
                        String _elem23;
                        for (int _i24 = 0; _i24 < _set22.size; ++_i24)
                        {
                          _elem23 = iprot.readString();
                          _val20.add(_elem23);
                        }
                        iprot.readSetEnd();
                      }
                      _val16.put(_key19, _val20);
                    }
                    iprot.readMapEnd();
                  }
                  struct.excludeRules.put(_key15, _val16);
                }
                iprot.readMapEnd();
              }
              struct.setExcludeRulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IFCExportOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.repositoryPattern != null) {
        if (struct.isSetRepositoryPattern()) {
          oprot.writeFieldBegin(REPOSITORY_PATTERN_FIELD_DESC);
          oprot.writeString(struct.repositoryPattern);
          oprot.writeFieldEnd();
        }
      }
      if (struct.filePatterns != null) {
        if (struct.isSetFilePatterns()) {
          oprot.writeFieldBegin(FILE_PATTERNS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.filePatterns.size()));
            for (String _iter25 : struct.filePatterns)
            {
              oprot.writeString(_iter25);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.includeRules != null) {
        if (struct.isSetIncludeRules()) {
          oprot.writeFieldBegin(INCLUDE_RULES_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, struct.includeRules.size()));
            for (Map.Entry<String, Map<String,Set<String>>> _iter26 : struct.includeRules.entrySet())
            {
              oprot.writeString(_iter26.getKey());
              {
                oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, _iter26.getValue().size()));
                for (Map.Entry<String, Set<String>> _iter27 : _iter26.getValue().entrySet())
                {
                  oprot.writeString(_iter27.getKey());
                  {
                    oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, _iter27.getValue().size()));
                    for (String _iter28 : _iter27.getValue())
                    {
                      oprot.writeString(_iter28);
                    }
                    oprot.writeSetEnd();
                  }
                }
                oprot.writeMapEnd();
              }
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.excludeRules != null) {
        if (struct.isSetExcludeRules()) {
          oprot.writeFieldBegin(EXCLUDE_RULES_FIELD_DESC);
          {
            oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, struct.excludeRules.size()));
            for (Map.Entry<String, Map<String,Set<String>>> _iter29 : struct.excludeRules.entrySet())
            {
              oprot.writeString(_iter29.getKey());
              {
                oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, _iter29.getValue().size()));
                for (Map.Entry<String, Set<String>> _iter30 : _iter29.getValue().entrySet())
                {
                  oprot.writeString(_iter30.getKey());
                  {
                    oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, _iter30.getValue().size()));
                    for (String _iter31 : _iter30.getValue())
                    {
                      oprot.writeString(_iter31);
                    }
                    oprot.writeSetEnd();
                  }
                }
                oprot.writeMapEnd();
              }
            }
            oprot.writeMapEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IFCExportOptionsTupleSchemeFactory implements SchemeFactory {
    public IFCExportOptionsTupleScheme getScheme() {
      return new IFCExportOptionsTupleScheme();
    }
  }

  private static class IFCExportOptionsTupleScheme extends TupleScheme<IFCExportOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IFCExportOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRepositoryPattern()) {
        optionals.set(0);
      }
      if (struct.isSetFilePatterns()) {
        optionals.set(1);
      }
      if (struct.isSetIncludeRules()) {
        optionals.set(2);
      }
      if (struct.isSetExcludeRules()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetRepositoryPattern()) {
        oprot.writeString(struct.repositoryPattern);
      }
      if (struct.isSetFilePatterns()) {
        {
          oprot.writeI32(struct.filePatterns.size());
          for (String _iter32 : struct.filePatterns)
          {
            oprot.writeString(_iter32);
          }
        }
      }
      if (struct.isSetIncludeRules()) {
        {
          oprot.writeI32(struct.includeRules.size());
          for (Map.Entry<String, Map<String,Set<String>>> _iter33 : struct.includeRules.entrySet())
          {
            oprot.writeString(_iter33.getKey());
            {
              oprot.writeI32(_iter33.getValue().size());
              for (Map.Entry<String, Set<String>> _iter34 : _iter33.getValue().entrySet())
              {
                oprot.writeString(_iter34.getKey());
                {
                  oprot.writeI32(_iter34.getValue().size());
                  for (String _iter35 : _iter34.getValue())
                  {
                    oprot.writeString(_iter35);
                  }
                }
              }
            }
          }
        }
      }
      if (struct.isSetExcludeRules()) {
        {
          oprot.writeI32(struct.excludeRules.size());
          for (Map.Entry<String, Map<String,Set<String>>> _iter36 : struct.excludeRules.entrySet())
          {
            oprot.writeString(_iter36.getKey());
            {
              oprot.writeI32(_iter36.getValue().size());
              for (Map.Entry<String, Set<String>> _iter37 : _iter36.getValue().entrySet())
              {
                oprot.writeString(_iter37.getKey());
                {
                  oprot.writeI32(_iter37.getValue().size());
                  for (String _iter38 : _iter37.getValue())
                  {
                    oprot.writeString(_iter38);
                  }
                }
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IFCExportOptions struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.repositoryPattern = iprot.readString();
        struct.setRepositoryPatternIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list39 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.filePatterns = new ArrayList<String>(_list39.size);
          String _elem40;
          for (int _i41 = 0; _i41 < _list39.size; ++_i41)
          {
            _elem40 = iprot.readString();
            struct.filePatterns.add(_elem40);
          }
        }
        struct.setFilePatternsIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TMap _map42 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, iprot.readI32());
          struct.includeRules = new HashMap<String,Map<String,Set<String>>>(2*_map42.size);
          String _key43;
          Map<String,Set<String>> _val44;
          for (int _i45 = 0; _i45 < _map42.size; ++_i45)
          {
            _key43 = iprot.readString();
            {
              org.apache.thrift.protocol.TMap _map46 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, iprot.readI32());
              _val44 = new HashMap<String,Set<String>>(2*_map46.size);
              String _key47;
              Set<String> _val48;
              for (int _i49 = 0; _i49 < _map46.size; ++_i49)
              {
                _key47 = iprot.readString();
                {
                  org.apache.thrift.protocol.TSet _set50 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
                  _val48 = new HashSet<String>(2*_set50.size);
                  String _elem51;
                  for (int _i52 = 0; _i52 < _set50.size; ++_i52)
                  {
                    _elem51 = iprot.readString();
                    _val48.add(_elem51);
                  }
                }
                _val44.put(_key47, _val48);
              }
            }
            struct.includeRules.put(_key43, _val44);
          }
        }
        struct.setIncludeRulesIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TMap _map53 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.MAP, iprot.readI32());
          struct.excludeRules = new HashMap<String,Map<String,Set<String>>>(2*_map53.size);
          String _key54;
          Map<String,Set<String>> _val55;
          for (int _i56 = 0; _i56 < _map53.size; ++_i56)
          {
            _key54 = iprot.readString();
            {
              org.apache.thrift.protocol.TMap _map57 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.SET, iprot.readI32());
              _val55 = new HashMap<String,Set<String>>(2*_map57.size);
              String _key58;
              Set<String> _val59;
              for (int _i60 = 0; _i60 < _map57.size; ++_i60)
              {
                _key58 = iprot.readString();
                {
                  org.apache.thrift.protocol.TSet _set61 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
                  _val59 = new HashSet<String>(2*_set61.size);
                  String _elem62;
                  for (int _i63 = 0; _i63 < _set61.size; ++_i63)
                  {
                    _elem62 = iprot.readString();
                    _val59.add(_elem62);
                  }
                }
                _val55.put(_key58, _val59);
              }
            }
            struct.excludeRules.put(_key54, _val55);
          }
        }
        struct.setExcludeRulesIsSet(true);
      }
    }
  }

}

