<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hawk_api_ifc" nsURI="http://github.com/mondo-hawk-ifc/hawk_api_ifc"
    nsPrefix="">
  <eAnnotations source="thrift">
    <details key="javans" value="org.hawk.service.ifc.api"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IFCExportOptions">
    <eAnnotations source="doc">
      <details key="d" value="Options for a server-side IFC export."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The repository for the query (or * for all repositories)"/>
        <details key="optional" value="true"/>
        <details key="default" value="*"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filePatterns" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="doc">
        <details key="d" value="The file patterns for the query (e.g. *.uml)"/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includeRules" eType="ecore:EClass ../../org.hawk.service.api/src/api.ecore#//EffectiveMetamodelMap"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="If set and not empty, only the specified metamodels, types and features will be fetched. Otherwise, everything that is not excluded will be fetched. The string '*' can be used to refer to all types within a metamodel or all fields within a type."/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="excludeRules" eType="ecore:EClass ../../org.hawk.service.api/src/api.ecore#//EffectiveMetamodelMap"
        containment="true">
      <eAnnotations source="doc">
        <details key="d" value="If set and not empty, the mentioned metamodels, types and features will not be fetched. The string '*' can be used to refer to all types within a metamodel or all fields within a type."/>
        <details key="optional" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IFCExportStatus">
    <eAnnotations source="doc">
      <details key="d" value="Status of a server-side IFC export job."/>
    </eAnnotations>
    <eLiterals name="SCHEDULED">
      <eAnnotations source="doc">
        <details key="d" value="The job has been scheduled but has not started yet."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="RUNNING" value="1">
      <eAnnotations source="doc">
        <details key="d" value="The job is currently running."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CANCELLED" value="2">
      <eAnnotations source="doc">
        <details key="d" value="The job has been cancelled."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FAILED" value="3">
      <eAnnotations source="doc">
        <details key="d" value="The job has failed."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DONE" value="4">
      <eAnnotations source="doc">
        <details key="d" value="The job is completed."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFCExportJob">
    <eAnnotations source="doc">
      <details key="d" value="Information about a server-side IFC export job."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//IFCExportStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IFCExport">
    <eAnnotations source="doc">
      <details key="d" value="IFC export facility for getting IFC models from the Hawk server"/>
    </eAnnotations>
    <eOperations name="exportAsSTEP" eType="#//IFCExportJob">
      <eAnnotations source="doc">
        <details key="d" value="Export part of a Hawk index in IFC STEP format"/>
      </eAnnotations>
      <eParameters name="hawkInstance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="options" eType="#//IFCExportOptions"/>
    </eOperations>
    <eOperations name="getJobs" upperBound="-1" eType="#//IFCExportJob">
      <eAnnotations source="doc">
        <details key="d" value="List all the previously scheduled IFC export jobs"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getJobStatus" eType="#//IFCExportJob">
      <eAnnotations source="doc">
        <details key="d" value="Retrieve the current status of the job with the specified ID"/>
      </eAnnotations>
      <eParameters name="jobID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="killJob" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="doc">
        <details key="d" value="Cancel the job with the specified ID"/>
      </eAnnotations>
      <eParameters name="jobID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>
</ecore:EPackage>
